"""Add sector

Revision ID: ead9de5dd384
Revises: fbb1e2cb82ba
Create Date: 2026-10-05 13:35:58.577651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ead9de5dd384'
down_revision: Union[str, Sequence[str], None] = 'fbb1e2cb82ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.Enum('HEALTHCARE', 'BANK', 'GOVERNMENT', 'SALON', 'SERVICE_CENTER', 'CLINIC', name='orgsector'), nullable=False))
        batch_op.drop_column('category')

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('queue_status',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.Enum('WAITING', 'CALLED', 'SERVING', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'BOOKED', 'CHECKED_IN', 'INSPECTION', 'IN_SERVICE', 'READY', name='queuestatus'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.alter_column('queue_status',
               existing_type=sa.Enum('WAITING', 'CALLED', 'SERVING', 'COMPLETED', 'CANCELLED', 'NO_SHOW', 'BOOKED', 'CHECKED_IN', 'INSPECTION', 'IN_SERVICE', 'READY', name='queuestatus'),
               type_=sa.VARCHAR(length=9),
               existing_nullable=True)

    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.VARCHAR(length=50), nullable=True))
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
