"""Add analytics indexes

Revision ID: fbb1e2cb82ba
Revises: fb07c5f903fc
Create Date: 2026-10-02 14:31:04.793366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbb1e2cb82ba'
down_revision: Union[str, Sequence[str], None] = 'fb07c5f903fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_branch_id'), ['branch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_service_id'), ['service_id'], unique=False)

    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_queue_entries_completed_at'), ['completed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entries_joined_at'), ['joined_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_queue_entries_started_at'), ['started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('queue_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_queue_entries_started_at'))
        batch_op.drop_index(batch_op.f('ix_queue_entries_joined_at'))
        batch_op.drop_index(batch_op.f('ix_queue_entries_completed_at'))

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_service_id'))
        batch_op.drop_index(batch_op.f('ix_appointments_branch_id'))

    # ### end Alembic commands ###
